### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by Aarnnity** [Ilhem23/change_lane_DQN#2]
Hi, firstly, thank you very much for your great work. 
I am a newbie and want to learn your project. However, after setting up the environment according to the "requirements.txt" file, there is an error at runtime. The error is as follows, I hope to get your help, thank you!

![image](https://user-images.githubusercontent.com/66675156/153837715-8723612d-35ae-493c-b2bd-9ecfc7c690e5.png)

**Comment by Ilhem23** [comment]
i added new network (circle one) in folder networks/highway because this network do not work for me, and change in sumo_env.py the path like this: def start(self, gui=False, numVehicles=100, vType='human', network_conf="networks/highway/sumoconfig.sumo.cfg",network_xml='networks/highway/highway.net.xml')

**Comment by Aarnnity** [comment]
> 

Yes, I know. I have modified the path as shown in the image below. So, I don't know what is causing the error.
![image](https://user-images.githubusercontent.com/66675156/153842204-0f7c75a3-a940-43e8-ba2c-949703ac7a8d.png)

**Comment by Ilhem23** [comment]
I upload for you a new network, work with the new one, the old didn't work

**Comment by Aarnnity** [comment]
> 
  OK, thank you, I'll try it later.

**Comment by Aarnnity** [comment]
> I upload for you a new network, work with the new one, the old didn't work

Hello, sorry to bother you again, I would like to ask you one more question.
First, I ran your latest committed project file. Still there is the error at the beginning (note: the relevant file path has been modified). The specific errors are as follows:
![3dbb725cff9946ffd01b98ce02d48a0](https://user-images.githubusercontent.com/66675156/154512211-c3a6dcb8-bbe4-4ac4-9a08-9fad6a477488.png)

![2668b0d635544c6dec5eead6245c650](https://user-images.githubusercontent.com/66675156/154512306-20a515b7-972d-4c5c-888d-b11cdc1988df.png)

I also searched for some information and tried to change the file name of sumoconfig.sumo.cfg to sumoconfig.sumocfg, but the same error still occurs in the end. 
So, do you have any advice on this? Hope to get your reply, thank you.

**Comment by Aarnnity** [comment]
> I upload for you a new network, work with the new one, the old didn't work

OK, the issue is resolved, thank you!
